#回调端口
server:
  port: 9988

#监听端口信息
robot:
  host: localhost
  port: 7788
  token: 666

#编码类型
spring:
  http:
    encoding:
      charset: UTF-8
  #国际化
  messages:
    #配置路径
    basename: i18n/messages
    #字符集
    encoding: UTF-8
  jackson:
    #格式化输出
    serialization.indent_output: true
    #时区
    time-zone: GMT+8
  datasource:
    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    #数据库连接池
    type: com.zaxxer.hikari.HikariDataSource
    #数据库用户名
    username: root
    #数据库密码
    password: password
    #连接池信息
    hikari:
      #最大连接数,默认值10.
      maximum-pool-size: 100
      #最小空闲连接，默认值10.
      minimum-idle: 20
      #连接超时时间(毫秒),默认值30秒.
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000(10分钟),只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 600000
      #如果大于等于 max-lifetime 且 max-lifetime>0,则会被重置为0.
      max-lifetime: 3000000
      #连接最大存活时间,默认值30分钟.设置应该比mysql设置的超时时间短
      connection-test-query: select 1

